language: python

branches:
  only:
    - master

dist: xenial
sudo: true

addons:
  apt:
    packages:
    - libdb-dev

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7

install:
  - pip install -U pip setuptools wheel tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
